### ISSUE TITLE
`squares.set({}, "key[0][0]", "value")` throws an error

### ISSUE THREAD

**Issue by kuba-orlik** [dominicbarnes/square#3]
Here's the gist of it:

```
> squares.set({}, "key[0][0]", "value")
TypeError: acc.push is not a function
    at /home/kuba/projects/sealcode/sealious/www-server/node_modules/squares/index.js:60:11
    at Array.reduce (native)
    at Object.exports.set (/home/kuba/projects/sealcode/sealious/www-server/node_modules/squares/index.js:39:29)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

Which is weird, as it works perfectly fine for this case:

```
> squares.set({}, "key[a][a]", "value")
{ key: { a: { a: 'value' } } }
```

**Comment by dominicbarnes** [comment]
Hmm... what version of node did you run this on? I just tried it on 6.3.0 and it worked without trouble, so maybe it's a problem with a specific version.

**Comment by dominicbarnes** [comment]
Ah wait, the version published on npm is significantly different than what I still have in this repo. (see #2) I'll need to merge all those upstream changes and add a test-case so this can be fixed.
